// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package postivo

import (
	"github.com/postivo/go-client/internal/config"
	"github.com/postivo/go-client/internal/hooks"
)

type AddressBook struct {
	Contacts *Contacts
	Groups   *Groups

	rootSDK          *Client
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newAddressBook(rootSDK *Client, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *AddressBook {
	return &AddressBook{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Contacts:         newContacts(rootSDK, sdkConfig, hooks),
		Groups:           newGroups(rootSDK, sdkConfig, hooks),
	}
}
