// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type AddContactByExtIDToGroupRequest struct {
	// External (custom) ID of the contact to add to the group.
	ExtID string `pathParam:"style=simple,explode=false,name=ext_id"`
	// Group `id` to associate with the contact.
	GroupID int64 `pathParam:"style=simple,explode=false,name=group_id"`
}

func (a *AddContactByExtIDToGroupRequest) GetExtID() string {
	if a == nil {
		return ""
	}
	return a.ExtID
}

func (a *AddContactByExtIDToGroupRequest) GetGroupID() int64 {
	if a == nil {
		return 0
	}
	return a.GroupID
}

type AddContactByExtIDToGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (a *AddContactByExtIDToGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddContactByExtIDToGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}

func (a *AddContactByExtIDToGroupResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
