// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type AddContactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (contact added).
	ContactResponse *components.ContactResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (a *AddContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddContactResponse) GetContactResponse() *components.ContactResponse {
	if a == nil {
		return nil
	}
	return a.ContactResponse
}

func (a *AddContactResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}

func (a *AddContactResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
