// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type AddContactToGroupRequest struct {
	// Global contact `id` to add to the group.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// Group `id` to associate with the contact.
	GroupID int64 `pathParam:"style=simple,explode=false,name=group_id"`
}

func (a *AddContactToGroupRequest) GetID() int64 {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *AddContactToGroupRequest) GetGroupID() int64 {
	if a == nil {
		return 0
	}
	return a.GroupID
}

type AddContactToGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (a *AddContactToGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddContactToGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}

func (a *AddContactToGroupResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
