// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type AddGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (group created).
	GroupResponse *components.GroupResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (a *AddGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddGroupResponse) GetGroupResponse() *components.GroupResponse {
	if a == nil {
		return nil
	}
	return a.GroupResponse
}

func (a *AddGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}

func (a *AddGroupResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
