// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type AddSenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (sender created).
	SenderDetails *components.SenderDetails
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (a *AddSenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddSenderResponse) GetSenderDetails() *components.SenderDetails {
	if a == nil {
		return nil
	}
	return a.SenderDetails
}

func (a *AddSenderResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}

func (a *AddSenderResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
