// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type CancelShipmentRequest struct {
	// Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
	Ids []string `pathParam:"style=simple,explode=true,name=ids"`
}

func (c *CancelShipmentRequest) GetIds() []string {
	if c == nil {
		return []string{}
	}
	return c.Ids
}

type CancelShipmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Check the shipment cancellation statuses in the response body.
	ShipmentCancellations []components.ShipmentCancellation
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (c *CancelShipmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelShipmentResponse) GetShipmentCancellations() []components.ShipmentCancellation {
	if c == nil {
		return nil
	}
	return c.ShipmentCancellations
}

func (c *CancelShipmentResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}

func (c *CancelShipmentResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
