// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type DeleteContactRequest struct {
	// Global contact `id` to remove.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteContactRequest) GetID() int64 {
	if d == nil {
		return 0
	}
	return d.ID
}

type DeleteContactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (d *DeleteContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteContactResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}

func (d *DeleteContactResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
