// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type DeleteContactByExternalIDRequest struct {
	// External (custom) ID of the contact to remove.
	ExtID string `pathParam:"style=simple,explode=false,name=ext_id"`
}

func (d *DeleteContactByExternalIDRequest) GetExtID() string {
	if d == nil {
		return ""
	}
	return d.ExtID
}

type DeleteContactByExternalIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (d *DeleteContactByExternalIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteContactByExternalIDResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}

func (d *DeleteContactByExternalIDResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
