// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetAccountDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully
	AccountResponse *components.AccountResponse
	// Unauthorized.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (g *GetAccountDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountDetailsResponse) GetAccountResponse() *components.AccountResponse {
	if g == nil {
		return nil
	}
	return g.AccountResponse
}

func (g *GetAccountDetailsResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
