// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetContactByExternalIDRequest struct {
	// External (custom) ID of the contact to fetch.
	ExtID string `pathParam:"style=simple,explode=false,name=ext_id"`
}

func (g *GetContactByExternalIDRequest) GetExtID() string {
	if g == nil {
		return ""
	}
	return g.ExtID
}

type GetContactByExternalIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Contact details are included in the response body.
	ContactResponse *components.ContactResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (g *GetContactByExternalIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetContactByExternalIDResponse) GetContactResponse() *components.ContactResponse {
	if g == nil {
		return nil
	}
	return g.ContactResponse
}

func (g *GetContactByExternalIDResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
