// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetContactByIDRequest struct {
	// Global contact `id` to fetch.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetContactByIDRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GetContactByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Contact details are included in the response body.
	ContactResponse *components.ContactResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (g *GetContactByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetContactByIDResponse) GetContactResponse() *components.ContactResponse {
	if g == nil {
		return nil
	}
	return g.ContactResponse
}

func (g *GetContactByIDResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
