// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetGroupByIDRequest struct {
	// Group id to fetch
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetGroupByIDRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GetGroupByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Group details are included in the response body.
	GroupResponse *components.GroupResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (g *GetGroupByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetGroupByIDResponse) GetGroupResponse() *components.GroupResponse {
	if g == nil {
		return nil
	}
	return g.GroupResponse
}

func (g *GetGroupByIDResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
