// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetSubaccountDetailsRequest struct {
	// Login of the subaccount (user) for which to retrieve data.
	UserLogin string `pathParam:"style=simple,explode=true,name=user_login"`
}

func (g *GetSubaccountDetailsRequest) GetUserLogin() string {
	if g == nil {
		return ""
	}
	return g.UserLogin
}

type GetSubaccountDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully
	AccountResponse *components.AccountResponse
	// Unauthorized.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (g *GetSubaccountDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSubaccountDetailsResponse) GetAccountResponse() *components.AccountResponse {
	if g == nil {
		return nil
	}
	return g.AccountResponse
}

func (g *GetSubaccountDetailsResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
