// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type GetStatusRequest struct {
	// Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
	Ids []string `pathParam:"style=simple,explode=true,name=ids"`
}

func (g *GetStatusRequest) GetIds() []string {
	if g == nil {
		return []string{}
	}
	return g.Ids
}

type GetStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Shipment details are included in the response body.
	StatusDetails []components.StatusDetails
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (g *GetStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStatusResponse) GetStatusDetails() []components.StatusDetails {
	if g == nil {
		return nil
	}
	return g.StatusDetails
}

func (g *GetStatusResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}

func (g *GetStatusResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
