// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type ListGroupsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Group details are included in the response body.
	GroupResponses []components.GroupResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (l *ListGroupsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListGroupsResponse) GetGroupResponses() []components.GroupResponse {
	if l == nil {
		return nil
	}
	return l.GroupResponses
}

func (l *ListGroupsResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
