// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type ListPredefinedConfigsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Predefined configuration details are included in the response body.
	PredefinedConfigs []components.PredefinedConfig
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (l *ListPredefinedConfigsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPredefinedConfigsResponse) GetPredefinedConfigs() []components.PredefinedConfig {
	if l == nil {
		return nil
	}
	return l.PredefinedConfigs
}

func (l *ListPredefinedConfigsResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
