// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type ListMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Metadata details are included in the response body.
	MetadataResponse *components.MetadataResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (l *ListMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListMetadataResponse) GetMetadataResponse() *components.MetadataResponse {
	if l == nil {
		return nil
	}
	return l.MetadataResponse
}

func (l *ListMetadataResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
