// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type ListSendersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Sender details are included in the response body.
	SenderDetails []components.SenderDetails
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (l *ListSendersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSendersResponse) GetSenderDetails() []components.SenderDetails {
	if l == nil {
		return nil
	}
	return l.SenderDetails
}

func (l *ListSendersResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
