// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type PingResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API service is available.
	PingResponse *components.PingResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
}

func (p *PingResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PingResponse) GetPingResponse() *components.PingResponse {
	if p == nil {
		return nil
	}
	return p.PingResponse
}

func (p *PingResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if p == nil {
		return nil
	}
	return p.ErrorResponse
}
