// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type RemoveContactFromGroupRequest struct {
	// Global contact `id` to detach from the group.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// Group `id` to detach from the contact.
	GroupID int64 `pathParam:"style=simple,explode=false,name=group_id"`
}

func (r *RemoveContactFromGroupRequest) GetID() int64 {
	if r == nil {
		return 0
	}
	return r.ID
}

func (r *RemoveContactFromGroupRequest) GetGroupID() int64 {
	if r == nil {
		return 0
	}
	return r.GroupID
}

type RemoveContactFromGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (r *RemoveContactFromGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RemoveContactFromGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if r == nil {
		return nil
	}
	return r.ErrorResponse
}

func (r *RemoveContactFromGroupResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}
