// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type RemoveContactByExtIDToGroupRequest struct {
	// External (custom) ID of the contact to detach from the group.
	ExtID string `pathParam:"style=simple,explode=false,name=ext_id"`
	// Group `id` to detach from the contact.
	GroupID int64 `pathParam:"style=simple,explode=false,name=group_id"`
}

func (r *RemoveContactByExtIDToGroupRequest) GetExtID() string {
	if r == nil {
		return ""
	}
	return r.ExtID
}

func (r *RemoveContactByExtIDToGroupRequest) GetGroupID() int64 {
	if r == nil {
		return 0
	}
	return r.GroupID
}

type RemoveContactByExtIDToGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (r *RemoveContactByExtIDToGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RemoveContactByExtIDToGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if r == nil {
		return nil
	}
	return r.ErrorResponse
}

func (r *RemoveContactByExtIDToGroupResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}
