// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type ShipmentPriceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully. Check each shipment’s price in the response body.
	ShipmentPrices []components.ShipmentPrice
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (s *ShipmentPriceResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ShipmentPriceResponse) GetShipmentPrices() []components.ShipmentPrice {
	if s == nil {
		return nil
	}
	return s.ShipmentPrices
}

func (s *ShipmentPriceResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if s == nil {
		return nil
	}
	return s.ErrorResponse
}

func (s *ShipmentPriceResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
