// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type UpdateGroupRequest struct {
	// Group `id` to update.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// A `Group` object with the updated fields.
	Group components.Group `request:"mediaType=application/json"`
}

func (u *UpdateGroupRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateGroupRequest) GetGroup() components.Group {
	if u == nil {
		return components.Group{}
	}
	return u.Group
}

type UpdateGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (group updated).
	GroupResponse *components.GroupResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (u *UpdateGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateGroupResponse) GetGroupResponse() *components.GroupResponse {
	if u == nil {
		return nil
	}
	return u.GroupResponse
}

func (u *UpdateGroupResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}

func (u *UpdateGroupResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
