// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type UpdateContactRequest struct {
	// ID of the contact to update.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// A `Contact` object with the updated fields.
	Contact components.Contact `request:"mediaType=application/json"`
}

func (u *UpdateContactRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateContactRequest) GetContact() components.Contact {
	if u == nil {
		return components.Contact{}
	}
	return u.Contact
}

type UpdateContactResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (contact updated).
	ContactResponse *components.ContactResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (u *UpdateContactResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateContactResponse) GetContactResponse() *components.ContactResponse {
	if u == nil {
		return nil
	}
	return u.ContactResponse
}

func (u *UpdateContactResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}

func (u *UpdateContactResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
