// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

type UpdateContactByExternalIDRequest struct {
	// External (custom) ID of the contact to update.
	ExtID string `pathParam:"style=simple,explode=false,name=ext_id"`
	// A `Contact` object with the updated fields.
	Contact components.Contact `request:"mediaType=application/json"`
}

func (u *UpdateContactByExternalIDRequest) GetExtID() string {
	if u == nil {
		return ""
	}
	return u.ExtID
}

func (u *UpdateContactByExternalIDRequest) GetContact() components.Contact {
	if u == nil {
		return components.Contact{}
	}
	return u.Contact
}

type UpdateContactByExternalIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request was processed successfully (contact updated).
	ContactResponse *components.ContactResponse
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (u *UpdateContactByExternalIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateContactByExternalIDResponse) GetContactResponse() *components.ContactResponse {
	if u == nil {
		return nil
	}
	return u.ContactResponse
}

func (u *UpdateContactByExternalIDResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}

func (u *UpdateContactByExternalIDResponse) GetHeaders() map[string][]string {
	if u == nil {
		return map[string][]string{}
	}
	return u.Headers
}
