// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/postivo/go-client/models/components"
	"github.com/postivo/go-client/optionalnullable"
)

// VerifySenderRequestBody - Verification code received in the letter.
type VerifySenderRequestBody struct {
	VerificationCode string `json:"verification_code"`
}

func (v *VerifySenderRequestBody) GetVerificationCode() string {
	if v == nil {
		return ""
	}
	return v.VerificationCode
}

type VerifySenderRequest struct {
	// ID of the sender to verify.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// Verification code received in the letter.
	RequestBody VerifySenderRequestBody `request:"mediaType=application/json"`
}

func (v *VerifySenderRequest) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *VerifySenderRequest) GetRequestBody() VerifySenderRequestBody {
	if v == nil {
		return VerifySenderRequestBody{}
	}
	return v.RequestBody
}

type VerifySenderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request.
	ErrorResponse optionalnullable.OptionalNullable[components.ErrorResponse]
	Headers       map[string][]string
}

func (v *VerifySenderResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VerifySenderResponse) GetErrorResponse() optionalnullable.OptionalNullable[components.ErrorResponse] {
	if v == nil {
		return nil
	}
	return v.ErrorResponse
}

func (v *VerifySenderResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
