// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/postivo/go-client/optionalnullable"
)

// AccountType - Account type.
type AccountType string

const (
	// AccountTypePrePaid Account type PRE-PAID
	AccountTypePrePaid AccountType = "PRE-PAID"
	// AccountTypePostPaid Account type POST-PAID
	AccountTypePostPaid AccountType = "POST-PAID"
)

func (e AccountType) ToPointer() *AccountType {
	return &e
}
func (e *AccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PRE-PAID":
		fallthrough
	case "POST-PAID":
		*e = AccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountType: %v", v)
	}
}

// AccountResponse - Account details, including balance and limits.
type AccountResponse struct {
	// User login.
	Login *string `json:"login,omitempty"`
	// Account type.
	AccountType *AccountType `json:"account_type,omitempty"`
	// Account limit.
	Limit *float32 `json:"limit,omitempty"`
	// Current account balance.
	Credit *float32 `json:"credit,omitempty"`
	// Subaccount credit balance; null if unlimited.
	Subcredit optionalnullable.OptionalNullable[float32] `json:"subcredit,omitempty"`
	// Account currency.
	Currency *string `json:"currency,omitempty"`
	// User full name.
	Name *string `json:"name,omitempty"`
	// Indicates whether this is the main account.
	IsMain *bool `json:"is_main,omitempty"`
}

func (a *AccountResponse) GetLogin() *string {
	if a == nil {
		return nil
	}
	return a.Login
}

func (a *AccountResponse) GetAccountType() *AccountType {
	if a == nil {
		return nil
	}
	return a.AccountType
}

func (a *AccountResponse) GetLimit() *float32 {
	if a == nil {
		return nil
	}
	return a.Limit
}

func (a *AccountResponse) GetCredit() *float32 {
	if a == nil {
		return nil
	}
	return a.Credit
}

func (a *AccountResponse) GetSubcredit() optionalnullable.OptionalNullable[float32] {
	if a == nil {
		return nil
	}
	return a.Subcredit
}

func (a *AccountResponse) GetCurrency() *string {
	if a == nil {
		return nil
	}
	return a.Currency
}

func (a *AccountResponse) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AccountResponse) GetIsMain() *bool {
	if a == nil {
		return nil
	}
	return a.IsMain
}
