// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
	"github.com/postivo/go-client/optionalnullable"
)

// ContactResponse - Contact details returned by the API for an Address Book entry.
type ContactResponse struct {
	// Name (person or company) — line 1.
	Name *string `json:"name"`
	// Name (person or company) — line 2.
	Name2 optionalnullable.OptionalNullable[string] `json:"name2,omitempty"`
	// Street address.
	Address *string `json:"address"`
	// Building number.
	HomeNumber optionalnullable.OptionalNullable[string] `json:"home_number,omitempty"`
	// Apartment (unit) number.
	FlatNumber optionalnullable.OptionalNullable[string] `json:"flat_number,omitempty"`
	// Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
	PostCode *string `json:"post_code"`
	// City.
	City *string `json:"city"`
	// Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased. Full list: https://www.iso.org/iso-3166-country-codes.html
	Country optionalnullable.OptionalNullable[string] `default:"PL" json:"country"`
	// Phone number (E.164 format recommended).
	PhoneNumber optionalnullable.OptionalNullable[string] `json:"phone_number,omitempty"`
	// Custom (external) contact ID; must be unique per contact.
	ExtID optionalnullable.OptionalNullable[string] `json:"ext_id,omitempty"`
	// IDs of groups the contact belongs to.
	GroupIds optionalnullable.OptionalNullable[[]int64] `json:"group_ids,omitempty"`
	// Unique system-assigned contact ID.
	ID int64 `json:"id"`
}

func (c ContactResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContactResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (c *ContactResponse) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ContactResponse) GetName2() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Name2
}

func (c *ContactResponse) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *ContactResponse) GetHomeNumber() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.HomeNumber
}

func (c *ContactResponse) GetFlatNumber() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.FlatNumber
}

func (c *ContactResponse) GetPostCode() *string {
	if c == nil {
		return nil
	}
	return c.PostCode
}

func (c *ContactResponse) GetCity() *string {
	if c == nil {
		return nil
	}
	return c.City
}

func (c *ContactResponse) GetCountry() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Country
}

func (c *ContactResponse) GetPhoneNumber() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.PhoneNumber
}

func (c *ContactResponse) GetExtID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ExtID
}

func (c *ContactResponse) GetGroupIds() optionalnullable.OptionalNullable[[]int64] {
	if c == nil {
		return nil
	}
	return c.GroupIds
}

func (c *ContactResponse) GetID() int64 {
	if c == nil {
		return 0
	}
	return c.ID
}
