// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
)

// DocumentMock - Mock document used to simulate page count for pricing without uploading a real file.
type DocumentMock struct {
	// Number of pages in the mock document.
	Pages int64 `json:"pages"`
}

func (d DocumentMock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentMock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"pages"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentMock) GetPages() int64 {
	if d == nil {
		return 0
	}
	return d.Pages
}
