// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DocumentResponse - Generated document content.
type DocumentResponse struct {
	// Document MIME type.
	MimeType string `json:"mime_type"`
	// Base64-encoded document content.
	FileStream *string `json:"file_stream,omitempty"`
}

func (d *DocumentResponse) GetMimeType() string {
	if d == nil {
		return ""
	}
	return d.MimeType
}

func (d *DocumentResponse) GetFileStream() *string {
	if d == nil {
		return nil
	}
	return d.FileStream
}
