// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
	"github.com/postivo/go-client/optionalnullable"
)

// DocumentPdf - PDF document payload.
type DocumentPdf struct {
	// Base64-encoded PDF content.
	FileStream string `json:"file_stream"`
	// Optional file name for identification purposes.
	FileName optionalnullable.OptionalNullable[string] `default:"null" json:"file_name"`
}

func (d DocumentPdf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentPdf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"file_stream"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentPdf) GetFileStream() string {
	if d == nil {
		return ""
	}
	return d.FileStream
}

func (d *DocumentPdf) GetFileName() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.FileName
}
