// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
)

// DocumentLibrary - A document from the user's account library.
type DocumentLibrary struct {
	// ID of the document stored in the user’s document library.
	ID int64 `json:"id"`
}

func (d DocumentLibrary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentLibrary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentLibrary) GetID() int64 {
	if d == nil {
		return 0
	}
	return d.ID
}
