// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorResponse - Problem Details object (RFC 9457) describing the error.
type ErrorResponse struct {
	// URI that identifies the problem type.
	Type *string `json:"type,omitempty"`
	// HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int64 `json:"status,omitempty"`
	// Short, human-readable summary of the problem type.
	Title *string `json:"title,omitempty"`
	// Human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// API-specific error code to help the provider team classify the error.
	Code *string `json:"code,omitempty"`
	// URI that identifies this specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`
}

func (e *ErrorResponse) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *ErrorResponse) GetStatus() *int64 {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ErrorResponse) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *ErrorResponse) GetDetail() *string {
	if e == nil {
		return nil
	}
	return e.Detail
}

func (e *ErrorResponse) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *ErrorResponse) GetInstance() *string {
	if e == nil {
		return nil
	}
	return e.Instance
}
