// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/optionalnullable"
)

// GroupResponse - Address Book group details returned by the API.
type GroupResponse struct {
	// Group name.
	Name string `json:"name"`
	// Optional group description.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// Unique system-assigned group ID.
	ID int64 `json:"id"`
}

func (g *GroupResponse) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GroupResponse) GetDescription() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GroupResponse) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}
