// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/optionalnullable"
)

// Group - Contact group definition in the Address Book.
type Group struct {
	// Group name.
	Name string `json:"name"`
	// Optional group description.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
}

func (g *Group) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *Group) GetDescription() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Description
}
