// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
	"github.com/postivo/go-client/optionalnullable"
)

// Recipient data for a shipment, including full postal address.
type Recipient struct {
	// Name (person or company) — line 1.
	Name *string `json:"name"`
	// Name (person or company) — line 2.
	Name2 optionalnullable.OptionalNullable[string] `json:"name2,omitempty"`
	// Street address.
	Address *string `json:"address"`
	// Building number.
	HomeNumber optionalnullable.OptionalNullable[string] `json:"home_number,omitempty"`
	// Apartment (unit) number.
	FlatNumber optionalnullable.OptionalNullable[string] `json:"flat_number,omitempty"`
	// Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
	PostCode *string `json:"post_code"`
	// City.
	City *string `json:"city"`
	// Country code in ISO 3166-1 alpha-2 format. Default: "PL". Value is automatically uppercased. Full list: https://www.iso.org/iso-3166-country-codes.html
	Country optionalnullable.OptionalNullable[string] `default:"PL" json:"country"`
	// Phone number (E.164 format recommended).
	PhoneNumber optionalnullable.OptionalNullable[string] `json:"phone_number,omitempty"`
	// Optional postscript printed above the recipient data on the envelope.
	Postscript optionalnullable.OptionalNullable[string] `json:"postscript,omitempty"`
}

func (r Recipient) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Recipient) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Recipient) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *Recipient) GetName2() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Name2
}

func (r *Recipient) GetAddress() *string {
	if r == nil {
		return nil
	}
	return r.Address
}

func (r *Recipient) GetHomeNumber() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.HomeNumber
}

func (r *Recipient) GetFlatNumber() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.FlatNumber
}

func (r *Recipient) GetPostCode() *string {
	if r == nil {
		return nil
	}
	return r.PostCode
}

func (r *Recipient) GetCity() *string {
	if r == nil {
		return nil
	}
	return r.City
}

func (r *Recipient) GetCountry() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Country
}

func (r *Recipient) GetPhoneNumber() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.PhoneNumber
}

func (r *Recipient) GetPostscript() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Postscript
}
