// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
	"github.com/postivo/go-client/optionalnullable"
)

// RecipientFromAddressBookByExternalID - Select shipment recipient data from the Address Book by external (custom) ID.
type RecipientFromAddressBookByExternalID struct {
	// External (custom) ID of the recipient stored in your Address Book.
	ExtID string `json:"ext_id"`
	// Set to true to fetch recipient data by external ID from inherited main account’s Address Book.
	Inherited *bool `default:"false" json:"inherited"`
	// Custom shipment ID assigned by the user.
	CustomID optionalnullable.OptionalNullable[string] `default:"null" json:"custom_id"`
	// Optional postscript printed above the recipient data on the envelope.
	Postscript optionalnullable.OptionalNullable[string] `json:"postscript,omitempty"`
}

func (r RecipientFromAddressBookByExternalID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RecipientFromAddressBookByExternalID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"ext_id"}); err != nil {
		return err
	}
	return nil
}

func (r *RecipientFromAddressBookByExternalID) GetExtID() string {
	if r == nil {
		return ""
	}
	return r.ExtID
}

func (r *RecipientFromAddressBookByExternalID) GetInherited() *bool {
	if r == nil {
		return nil
	}
	return r.Inherited
}

func (r *RecipientFromAddressBookByExternalID) GetCustomID() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.CustomID
}

func (r *RecipientFromAddressBookByExternalID) GetPostscript() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Postscript
}
