// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/internal/utils"
	"github.com/postivo/go-client/optionalnullable"
)

// RecipientFromAddressBook - Select recipient data for a shipment from the Address Book.
type RecipientFromAddressBook struct {
	// Global ID of the recipient stored in the personal Address Book.
	ID int64 `json:"id"`
	// User-assigned custom shipment ID.
	CustomID optionalnullable.OptionalNullable[string] `default:"null" json:"custom_id"`
	// Optional postscript printed above the recipient data on the envelope.
	Postscript optionalnullable.OptionalNullable[string] `json:"postscript,omitempty"`
}

func (r RecipientFromAddressBook) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RecipientFromAddressBook) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (r *RecipientFromAddressBook) GetID() int64 {
	if r == nil {
		return 0
	}
	return r.ID
}

func (r *RecipientFromAddressBook) GetCustomID() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.CustomID
}

func (r *RecipientFromAddressBook) GetPostscript() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.Postscript
}
