// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Bearer *string `security:"scheme,type=http,subtype=bearer,name=Authorization,env=client_bearer"`
}

func (s *Security) GetBearer() *string {
	if s == nil {
		return nil
	}
	return s.Bearer
}
