// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SenderDetails - Extended sender details.
type SenderDetails struct {
	// Unique sender ID.
	ID *int64 `json:"id,omitempty"`
	// Sender data for the shipment.
	Sender Sender `json:"sender"`
	// Indicates whether the sender is active.
	Active bool `json:"active"`
	// Indicates whether this is the default sender.
	Default bool `json:"default"`
}

func (s *SenderDetails) GetID() *int64 {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SenderDetails) GetSender() Sender {
	if s == nil {
		return Sender{}
	}
	return s.Sender
}

func (s *SenderDetails) GetActive() bool {
	if s == nil {
		return false
	}
	return s.Active
}

func (s *SenderDetails) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}
