// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/optionalnullable"
)

// Sender data for the shipment.
type Sender struct {
	// Sender name (person or company) — line 1.
	Name *string `json:"name"`
	// Sender name (person or company) — line 2.
	Name2 optionalnullable.OptionalNullable[string] `json:"name2,omitempty"`
	// Street address of the sender.
	Address *string `json:"address"`
	// Building number of the sender.
	HomeNumber optionalnullable.OptionalNullable[string] `json:"home_number,omitempty"`
	// Apartment (unit) number of the sender.
	FlatNumber optionalnullable.OptionalNullable[string] `json:"flat_number,omitempty"`
	// Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
	PostCode *string `json:"post_code"`
	// City of the sender.
	City *string `json:"city"`
	// Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list: https://www.iso.org/iso-3166-country-codes.html
	Country optionalnullable.OptionalNullable[string] `json:"country,omitempty"`
}

func (s *Sender) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Sender) GetName2() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Name2
}

func (s *Sender) GetAddress() *string {
	if s == nil {
		return nil
	}
	return s.Address
}

func (s *Sender) GetHomeNumber() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.HomeNumber
}

func (s *Sender) GetFlatNumber() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.FlatNumber
}

func (s *Sender) GetPostCode() *string {
	if s == nil {
		return nil
	}
	return s.PostCode
}

func (s *Sender) GetCity() *string {
	if s == nil {
		return nil
	}
	return s.City
}

func (s *Sender) GetCountry() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Country
}
