// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/optionalnullable"
)

// ShipmentCancellation - Result of cancelling a single shipment
type ShipmentCancellation struct {
	// Shipment ID.
	ID *string `json:"id,omitempty"`
	// Cancellation status code (`204` if cancelled successfully; otherwise an error code).
	Status *int64 `json:"status,omitempty"`
	// Problem Details object (RFC 9457) describing the error.
	Error optionalnullable.OptionalNullable[ErrorResponse] `json:"error,omitempty"`
}

func (s *ShipmentCancellation) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ShipmentCancellation) GetStatus() *int64 {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *ShipmentCancellation) GetError() optionalnullable.OptionalNullable[ErrorResponse] {
	if s == nil {
		return nil
	}
	return s.Error
}
