// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/postivo/go-client/optionalnullable"
)

// StatusDetails - Details of a single shipment and its status events
type StatusDetails struct {
	// Single shipment details
	ShipmentDetails *ShipmentDetails `json:"shipment_details,omitempty"`
	// List of status events for the shipment.
	StatusEvents optionalnullable.OptionalNullable[[]StatusEvent] `json:"status_events,omitempty"`
}

func (s *StatusDetails) GetShipmentDetails() *ShipmentDetails {
	if s == nil {
		return nil
	}
	return s.ShipmentDetails
}

func (s *StatusDetails) GetStatusEvents() optionalnullable.OptionalNullable[[]StatusEvent] {
	if s == nil {
		return nil
	}
	return s.StatusEvents
}
