// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"github.com/postivo/go-client/models/components"
)

// ErrorResponse - Problem Details object (RFC 9457) describing the error.
type ErrorResponse struct {
	// URI that identifies the problem type.
	Type *string `json:"type,omitempty"`
	// HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int64 `json:"status,omitempty"`
	// Short, human-readable summary of the problem type.
	Title *string `json:"title,omitempty"`
	// Human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// API-specific error code to help the provider team classify the error.
	Code *string `json:"code,omitempty"`
	// URI that identifies this specific occurrence of the problem.
	Instance *string                 `json:"instance,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	if e.Detail == nil {
		return "unknown error"
	}

	return *e.Detail
}
